import type { Recipe } from './types';

export const sampleRecipes: Recipe[] = [
  {
    id: 'sample-braised-beans',
    title: 'Tomato-braised butter beans',
    ingredients: [
      '2 tablespoons olive oil',
      '3 garlic cloves, thinly sliced',
      '1 × 400 g can butter beans, drained',
      '1 × 400 g can crushed tomatoes',
      '1 teaspoon smoked paprika',
      '1 handful flat-leaf parsley',
      'Salt and black pepper',
    ],
    steps: [
      'Warm the olive oil in a wide pan over medium heat.',
      'Cook the garlic for 30 seconds. Add the beans, tomatoes, and paprika.',
      'Simmer for 18 minutes, until the sauce coats the beans.',
      'Season, fold in the parsley, and serve with toast.',
    ],
    yield: 'Serves 3',
    notes: 'Add a spoonful of yogurt at the table. Leftovers keep for two days.',
    sourceName: 'Mara’s kitchen notebook',
    sourceUrl: '',
    categories: ['Weeknight', 'Beans'],
    createdAt: '2026-06-03T10:00:00.000Z',
    updatedAt: '2026-06-03T10:00:00.000Z',
  },
  {
    id: 'sample-lemon-cake',
    title: 'Lemon olive oil cake',
    ingredients: [
      '180 g plain flour',
      '1½ teaspoons baking powder',
      '3 eggs',
      '160 g caster sugar',
      '120 ml olive oil',
      '2 lemons, zest and juice',
    ],
    steps: [
      'Heat the oven to 175°C. Line a 20 cm round tin.',
      'Whisk the eggs and sugar until pale. Slowly whisk in the oil.',
      'Fold in the flour, baking powder, lemon zest, and 40 ml juice.',
      'Bake for 32–36 minutes. Cool before lifting from the tin.',
    ],
    yield: 'Makes one 20 cm cake',
    notes: 'The flavour improves overnight. Keep covered at room temperature.',
    sourceName: 'Family recipe card',
    sourceUrl: '',
    categories: ['Baking', 'Cake'],
    createdAt: '2026-05-18T14:00:00.000Z',
    updatedAt: '2026-05-18T14:00:00.000Z',
  },
  {
    id: 'sample-noodle-salad',
    title: 'Cold sesame noodle salad',
    ingredients: [
      '250 g wheat noodles',
      '2 tablespoons sesame paste or tahini',
      '1 tablespoon soy sauce',
      '1 tablespoon rice vinegar',
      '1 teaspoon chilli oil',
      '1 cucumber, cut into matchsticks',
      '2 spring onions, sliced',
    ],
    steps: [
      'Cook the noodles until just tender. Rinse under cold water.',
      'Whisk the sesame paste, soy sauce, vinegar, and chilli oil.',
      'Toss the noodles with the dressing, cucumber, and spring onions.',
      'Serve cool or pack for lunch.',
    ],
    yield: 'Serves 2',
    notes: 'Loosen the sauce with one tablespoon of noodle water if needed.',
    sourceName: 'Adapted from a handwritten lunch note',
    sourceUrl: '',
    categories: ['Lunch', 'Noodles'],
    createdAt: '2026-07-11T09:30:00.000Z',
    updatedAt: '2026-07-11T09:30:00.000Z',
  },
];
